In [10]:
import math
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [11]:
import numpy as np
weighted_sum = np.array([1.2, 0.9, 0.75, 0.8, 1.5])

def softmax(x):
  return np.exp(x) / np.sum(np.exp(x))

def relu(x):
  return np.maximum(0, x)

def bipolar_sigmoid(x, beta=1):
  return (1 - np.exp(-beta * x)) / (1 + np.exp(-beta * x))

output_softmax = softmax(weighted_sum)

output_relu = relu(weighted_sum)

output_sigmoid = bipolar_sigmoid(weighted_sum)

print("Softmax Output:", output_softmax)
print("ReLU Output:", output_relu)
print("Bipolar Sigmoid Output:", output_sigmoid)

Softmax Output: [0.22734376 0.1684204  0.14496078 0.15239308 0.30688198]
ReLU Output: [1.2  0.9  0.75 0.8  1.5 ]
Bipolar Sigmoid Output: [0.53704957 0.42189901 0.3583574  0.37994896 0.63514895]


In [10]:
#Import required libraries
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd
#Load the Iris dataset
iris = load_iris()
#View the iris data keys
iris.keys()

#it is a key of dictionary iris
iris.target_names
##Convert data and target into a data frame.
#Extract the First 100 Features
X = pd.DataFrame(data = iris.data[:100,:], columns = iris.feature_names)
X.head(100) #Inspect the features
#Target
y = pd.DataFrame(data=iris.target[:100], columns = ['irisType'])
y.head(100)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Perceptron classifier
mdlPercept = Perceptron()
# Train the classifier
mdlPercept.fit(X_train, y_train)
# Make predictions on the test set
y_pred = mdlPercept.predict(X_test)
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
#Generate the Confusion Matrix
print('Perceptron Confusion Matrix: confusion_matrix(y_test, y_pred)');


Accuracy: 1.0
Perceptron Confusion Matrix: confusion_matrix(y_test, y_pred)


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
#Import required libraries
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd


In [3]:
#Load the Iris dataset
iris=load_iris()

In [4]:
#View the iris data keys
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
#A key of dictionary iris
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
#Convert data and target into a data frame
#Extract the first 100 features
#Target
y= pd.DataFrame(data=iris.target[:100:],columns =['iris Type'])
y.head(100)

iris Type
0           0
1           0
2           0
3           0
4           0
..        ...
95          1
96          1
97          1
98          1
99          1

[100 rows x 1 columns]

In [49]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Perceptron classifier
mdlPercept = Perceptron()
# Train the classifier
mdlPercept.fit(X_train, y_train)
# Make predictions on the test set
y_pred = mdlPercept.predict(X_test)
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
#Generate the Confusion Matrix
#Generate the Confusion Matrix
print('Perceptron Confusion Matrix:\n',confusion_matrix(y_test, y_pred));


Accuracy: 0.96
Perceptron Confusion Matrix:
 [[13  0  0]
 [ 0  7  0]
 [ 0  1  4]]


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [47]:
# Import required libraries
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

In [48]:
# Load the Iris dataset
iris = load_iris()

In [32]:
# Convert data and target into a data frame
# Extract the First 100 Features
X = pd.DataFrame(data=iris.data[:100+(24%50), :], columns=iris.feature_names)
y = pd.DataFrame(data=iris.target[:100+(24%50)], columns=['irisType'])

In [33]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
# Convert targets to categorical (one-hot encoding)
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

In [44]:
# Define the Perceptron model using a single dense layer
model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, activation='softmax', input_shape=(X_train.shape[1],))
])

In [37]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=1, verbose=1)

Epoch 1/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6847 - loss: 0.6790  
Epoch 2/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6859 - loss: 0.6749
Epoch 3/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5670 - loss: 0.7170 
Epoch 4/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5664 - loss: 0.7536
Epoch 5/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5878 - loss: 0.7080
Epoch 6/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7022 - loss: 0.6060
Epoch 7/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7991 - loss: 0.5362
Epoch 8/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6941 - loss: 0.6095
Epoch 9/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8510 - loss: 0.5183
Epoch 10/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8229 - loss: 0.4692
Epoch 11/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8793 - loss: 0.4501
Epoch 12/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8442 -

In [41]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=1)
y_test_classes = y_test.argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


In [42]:
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test_classes, y_pred_classes)
print("Accuracy:", accuracy)

Accuracy: 0.8


In [40]:
# Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n", confusion_matrix(y_test_classes, y_pred_classes))

Perceptron Confusion Matrix:
 [[13  0  0]
 [ 0  5  2]
 [ 0  3  2]]
